### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by LixvYang** [rumsystem/quorum#168]
In the process of my development, I called the local port api through the axios library, and a CORS problem occurred. I referred to rum-app but still don't know how to solve it. The following is the problem description.

Here is my Typescript code.
```ts
axios.get('https://localhost:64147/api/v1/groups').then((res) => {
  console.log(res.status)
})
```

But it happened No access problem, it should be a configuration problem of my node.

<img width="383" alt="屏幕截图 2022-06-26 175820" src="https://user-images.githubusercontent.com/66065674/175809037-94957a88-4e88-49d0-9f76-5e5ea15a572a.png">

Emmm, should I add config with my axios code?

But when I open the api-groups on my brower, the problem disappeared。

<img width="960" alt="屏幕截图 2022-06-26 180251" src="https://user-images.githubusercontent.com/66065674/175809125-f254ab1c-076b-4c32-b5e6-4961f47eafce.png">

I view the source code of quorum, No CORS config. And, the bug plagued me for two days and interrupted my next work...

**Comment by liujuanjuan1984** [comment]
try to check `axios.defaults.baseURL` 

It seems that  param of `axios.get(param) `  should be endpoint ,not full-path-url

**Comment by LixvYang** [comment]
<img width="418" alt="屏幕截图 2022-06-26 220334" src="https://user-images.githubusercontent.com/66065674/175818092-36b2d400-797a-4288-9f7e-45797b5fef0b.png">
<img width="388" alt="屏幕截图 2022-06-26 220232" src="https://user-images.githubusercontent.com/66065674/175818095-bebbceba-6193-4846-a825-9b27f9452386.png">

It doesn't look like this is the problem...

**Comment by LixvYang** [comment]
Should be related to the configuration of the node.

**Comment by zhangwm404** [comment]
@LixvYang This is a CORS problem, please update the code to the latest of the main branch, the default setting of CORS is `allow *`, so it will work fine.

**Comment by LixvYang** [comment]
Thanks, the problem is solved.
