### ISSUE TITLE
Quic-go package does not support go1.20

### ISSUE THREAD

**Issue by LixvYang** [rumsystem/quorum#262]
Failed to compile rum on go v1.20

Will this be fixed in the future？

[https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions](https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions)

```
go build -ldflags "-s -w -X main.GitCommit=d0201949da01113ba1d9d7fb9d9130bb02a2443a" -o dist/linux_amd64/quorum main.go
# github.com/lucas-clemente/quic-go/internal/qtls
../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.29.1/internal/qtls/go120.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
make: *** [makefile:27: linux] Error 1
```

**Comment by huo-ju** [comment]
We are working on the new consensus on _consensus_2_main_ branch, and the main branch branch was archived. We will fix it on the _consensus_2_main_ branch but keep the main branch unchanged.  

The _consensus_2_main_ branch will become the default branch  in coming days. 

Thanks.
